# Generated by Django 5.2.13 on 2026-04-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEstado', models.CharField(max_length=50, unique=True, verbose_name='Estado')),
                ('descripcion_Estado', models.CharField(blank=True, max_length=255, null=True)),
                ('activo_Estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado de Cotización',
                'verbose_name_plural': 'Estados de Cotización',
                'db_table': 'Cat_Estado_Cotizacion',
            },
        ),
    ]
