# Generated by Django 5.2.13 on 2026-04-23 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes_Lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contacto', models.CharField(choices=[('WHATSAPP', 'Mensaje de WhatsApp'), ('CORREO', 'Correo Electrónico'), ('LLAMADA', 'Llamada Telefónica'), ('SOPORTE', 'Ticket de Soporte Técnico')], max_length=20, verbose_name='Tipo de Interacción')),
                ('detalles', models.TextField(verbose_name='Notas de la interacción')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del contacto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes_Lead.clientelead', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Seguimiento / Soporte',
                'verbose_name_plural': 'Bitácora de Seguimientos',
                'db_table': 'CRM_Seguimiento_Soporte',
            },
        ),
    ]
