# Generated by Django 5.2.13 on 2026-04-23 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seguimiento_Soporte', '0001_initial'),
        ('Solicitudes_Cotizaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientosoporte',
            name='cotizacion_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Solicitudes_Cotizaciones.solicitudcotizacion', verbose_name='Cotización Relacionada'),
        ),
        migrations.AddField(
            model_name='seguimientosoporte',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
