# Generated by Django 5.2.13 on 2026-04-23 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tipos_Empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Empresa', models.CharField(max_length=200, verbose_name='Empresa/Cliente')),
                ('contacto_principal', models.CharField(max_length=100, verbose_name='Nombre del Contacto')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('Fecha_Registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('es_cliente_activo', models.BooleanField(default=False, verbose_name='¿Ya es cliente final?')),
                ('RegistradoPor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('tipo_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tipos_Empresa.tipoempresa', verbose_name='Tipo de Empresa')),
            ],
            options={
                'verbose_name': 'Cliente o Lead',
                'verbose_name_plural': 'Clientes y Leads',
                'db_table': 'CRM_ Clientes_Lead',
            },
        ),
    ]
