# Generated by Django 5.2.13 on 2026-04-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo_Servicios_Productos', '0001_initial'),
        ('Clientes_Lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientelead',
            name='servicios_interes',
            field=models.ManyToManyField(blank=True, to='Catalogo_Servicios_Productos.servicioproducto', verbose_name='Servicios de Interés'),
        ),
    ]
