# Generated by Django 5.2.13 on 2026-05-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes_Lead', '0002_clientelead_servicios_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientelead',
            name='origen_lead',
            field=models.CharField(choices=[('Google Search', 'Google Search / Buscador'), ('Facebook Ads', 'Facebook Ads / Redes Sociales'), ('LinkedIn', 'LinkedIn / Profesional'), ('Directo', 'Tráfico Directo / Referencia')], default='Directo', max_length=50, verbose_name='Origen del Lead'),
        ),
    ]
