# Generated by Django 5.2.13 on 2026-04-23 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CategoriaProducto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=150, verbose_name='Nombre del Producto/Servicio')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('descripcionProducto', models.TextField(blank=True, null=True)),
                ('activo_producto', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CategoriaProducto.categoria_producto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Servicio o Producto',
                'verbose_name_plural': 'Servicios o Productos',
                'db_table': 'Cat_Servicios_Productos',
            },
        ),
    ]
