# Generated by Django 5.2.13 on 2026-04-23 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes_Lead', '0001_initial'),
        ('Estado_Cotizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True, verbose_name='Folio de Cotizacion')),
                ('descripcion_requerimiento', models.TextField(verbose_name='Requerimientos del Cliente')),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Estimado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('agente_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agente de Ventas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes_Lead.clientelead', verbose_name='Cliente / Lead')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Estado_Cotizacion.estadocotizacion', verbose_name='Estado actual')),
            ],
            options={
                'verbose_name': 'Solicitud de Cotización',
                'verbose_name_plural': 'Solicitudes y Cotizaciones',
                'db_table': 'CRM_Solicitudes_Cotizaciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
