# Generated by Django 5.2.13 on 2026-04-24 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo_Servicios_Productos', '0001_initial'),
        ('Solicitudes_Cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Solicitudes_Cotizaciones.solicitudcotizacion', verbose_name='Cotización')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Catalogo_Servicios_Productos.servicioproducto', verbose_name='Servicio / Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de la Cotización',
                'db_table': 'CRM_Detalle_Cotizaciones',
            },
        ),
    ]
