# Generated by Django 5.2.13 on 2026-04-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes_Cotizaciones', '0002_detallecotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecotizacion',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario'),
        ),
    ]
